# configs/a2c_configs.yaml

a2c:
  # overall training control
  total_timesteps: 150000   # total timesteps per run
  n_runs: 5                 # how many independent runs
  policy: "MlpPolicy"

  # A2C hyperparameters (SB3)
  learning_rate: 0.0007
  n_steps: 5
  gamma: 0.99
  gae_lambda: 0.95
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  rms_prop_eps: 0.00001
  use_rms_prop: true
  normalize_advantage: true
