# configs/ddpg_configs.yaml

ddpg:
  # overall training control
  total_timesteps: 150000
  n_runs: 5
  policy: "MlpPolicy"

  # DDPG hyperparameters (SB3)
  learning_rate: 0.001
  buffer_size: 1000000
  learning_starts: 10000
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: 64
  gradient_steps: 64
  action_noise_std: 0.1   # if you later decide to add NormalActionNoise in code
